import { useState, useMemo, useCallback, useRef, useEffect } from 'react';
import type { LucideIcon } from 'lucide-react';
import {
  Database,
  FolderOpen,
  Search,
  Github,
  Globe,
  Chrome,
  Code2,
  Bug,
  FileText,
  GitBranch,
  BookOpen,
  Zap,
  GitPullRequest,
  Clock,
  ChevronLeft,
  ChevronRight,
  Plug,
  Brain,
} from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Card, CardContent } from '@/components/ui/card';
import { Switch } from '@/components/ui/switch';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────

export type ToolCategory =
  | 'database'
  | 'filesystem'
  | 'search'
  | 'devops'
  | 'network'
  | 'browser'
  | 'code-execution'
  | 'scraping'
  | 'social'
  | 'code'
  | 'novel'
  | 'automation';

export interface MCPTool {
  id: string;
  name: string;
  description: string;
  category: ToolCategory;
  icon: string;
  enabled: boolean;
  source: 'official';
}

export interface Skill {
  id: string;
  name: string;
  description: string;
  category: ToolCategory;
  icon: string;
  enabled: boolean;
  source: 'clawhub' | 'self-evolved';
  autoGenerated?: boolean;
}

export type ToastType = 'success' | 'error';

export interface ToastState {
  message: string;
  type: ToastType;
  visible: boolean;
}

// ─────────────────────────────────────────────
// Icon Mapping
// ─────────────────────────────────────────────

const iconMap: Record<string, LucideIcon> = {
  database: Database,
  filesystem: FolderOpen,
  search: Search,
  devops: Github,
  network: Globe,
  browser: Chrome,
  'code-execution': Code2,
  scraping: Bug,
  social: FileText,
  code: GitBranch,
  novel: BookOpen,
  automation: Zap,
  GitPullRequest,
  Clock,
};

// ─────────────────────────────────────────────
// Category Labels (Chinese)
// ─────────────────────────────────────────────

const categoryLabels: Record<string, string> = {
  all: '全部',
  database: '数据库',
  search: '搜索',
  browser: '浏览器',
  filesystem: '文件',
  network: '网络',
  'code-execution': '代码执行',
  scraping: '抓取',
  devops: 'DevOps',
  social: '社交',
  code: '代码',
  novel: '小说',
  automation: '自动化',
};

// ─────────────────────────────────────────────
// Mock Data — MCP Tools
// ─────────────────────────────────────────────

const mcpTools: MCPTool[] = [
  { id: 'sqlite', name: 'SQLite 数据库', description: '本地 SQLite 数据库查询与数据持久化', category: 'database', icon: 'Database', enabled: true, source: 'official' },
  { id: 'filesystem', name: 'Filesystem', description: '文件系统读写与目录浏览', category: 'filesystem', icon: 'FolderOpen', enabled: true, source: 'official' },
  { id: 'brave-search', name: 'Brave Search', description: 'Brave 搜索引擎，实时联网搜索（需 API Key）', category: 'search', icon: 'Search', enabled: false, source: 'official' },
  { id: 'github', name: 'GitHub', description: '代码仓库操作、PR、Issue 管理（需 Token）', category: 'devops', icon: 'Github', enabled: false, source: 'official' },
  { id: 'fetch', name: 'Web Fetch', description: '网页内容抓取与 API 调用', category: 'network', icon: 'Globe', enabled: true, source: 'official' },
  { id: 'playwright', name: 'Playwright', description: '浏览器自动化、网页截图、元素操作', category: 'browser', icon: 'Chrome', enabled: false, source: 'official' },
  { id: 'pydantic-sandbox', name: 'Python Sandbox', description: '安全 Python 代码沙箱执行', category: 'code-execution', icon: 'Code2', enabled: false, source: 'official' },
  { id: 'apify', name: 'Apify', description: '3000+ 云工具，网页数据抓取（需 Token）', category: 'scraping', icon: 'Bug', enabled: false, source: 'official' },
];

// ─────────────────────────────────────────────
// Mock Data — Skills
// ─────────────────────────────────────────────

const skills: Skill[] = [
  { id: 'xiaohongshu_v1', name: '小红书爆款文案', description: '生成小红书风格的爆款文案，含标题、正文、标签', category: 'social', icon: 'FileText', enabled: true, source: 'clawhub' },
  { id: 'code_refactor_v2', name: '代码重构专家', description: '安全重构代码：提取函数、重命名变量、消除重复', category: 'code', icon: 'GitBranch', enabled: true, source: 'clawhub' },
  { id: 'novel_suspense_v1', name: '悬疑桥段设计', description: '悬疑桥段设计 + 伏笔提前 3 章埋设', category: 'novel', icon: 'BookOpen', enabled: true, source: 'self-evolved', autoGenerated: true },
  { id: 'frontend_bug_v1', name: '前端 Bug 修复', description: '前端 bug 修复 + 自动检查 imports 完整性', category: 'code', icon: 'Bug', enabled: true, source: 'self-evolved', autoGenerated: true },
  { id: 'scene_pacing_v2', name: '场景节奏控制', description: '场景描写节奏控制：慢热铺垫 + 转折加速', category: 'novel', icon: 'Clock', enabled: true, source: 'self-evolved', autoGenerated: true },
  { id: 'pr_description_v1', name: 'PR 描述生成', description: '自动生成 GitHub PR 描述，含变更摘要和测试说明', category: 'devops', icon: 'GitPullRequest', enabled: false, source: 'clawhub' },
];

// ─────────────────────────────────────────────
// Category Filter Tab Bar
// ─────────────────────────────────────────────

interface CategoryTabBarProps {
  categories: string[];
  active: string;
  onSelect: (cat: string) => void;
}

const CategoryTabBar: React.FC<CategoryTabBarProps> = ({
  categories,
  active,
  onSelect,
}) => {
  const scrollRef = useRef<HTMLDivElement>(null);

  const scroll = (dir: number) => {
    if (scrollRef.current) {
      scrollRef.current.scrollBy({ left: dir * 120, behavior: 'smooth' });
    }
  };

  return (
    <div className="relative flex items-center gap-1 bg-muted/50 rounded-lg p-1.5">
      <button
        onClick={() => scroll(-1)}
        className="shrink-0 w-7 h-7 flex items-center justify-center rounded-md hover:bg-muted transition-colors text-muted-foreground"
        type="button"
        aria-label="向左滚动"
      >
        <ChevronLeft className="w-4 h-4" />
      </button>

      <div
        ref={scrollRef}
        className="flex-1 flex gap-1 overflow-x-auto scrollbar-hide"
        style={{ scrollbarWidth: 'none' }}
      >
        {categories.map((cat) => (
          <button
            key={cat}
            onClick={() => onSelect(cat)}
            className={`
              shrink-0 px-3 py-1.5 rounded-md text-sm font-medium transition-all duration-200
              ${active === cat
                ? 'bg-background text-foreground shadow-sm border border-border/50'
                : 'text-muted-foreground hover:text-foreground hover:bg-muted'
              }
            `}
            type="button"
          >
            {categoryLabels[cat] || cat}
          </button>
        ))}
      </div>

      <button
        onClick={() => scroll(1)}
        className="shrink-0 w-7 h-7 flex items-center justify-center rounded-md hover:bg-muted transition-colors text-muted-foreground"
        type="button"
        aria-label="向右滚动"
      >
        <ChevronRight className="w-4 h-4" />
      </button>
    </div>
  );
};

// ─────────────────────────────────────────────
// Plugin / Skill Card
// ─────────────────────────────────────────────

interface CardItemProps {
  id: string;
  name: string;
  description: string;
  category: ToolCategory;
  icon: string;
  enabled: boolean;
  autoGenerated?: boolean;
  source: string;
  onToggle: (id: string, enabled: boolean) => void;
}

const CardItem: React.FC<CardItemProps> = ({
  id,
  name,
  description,
  category,
  icon,
  enabled,
  autoGenerated,
  onToggle,
}) => {
  const IconComponent = iconMap[icon] || Zap;

  return (
    <Card className="group relative overflow-hidden border-border/60 hover:border-border hover:shadow-md transition-all duration-200">
      {/* AI Auto-Generated Badge */}
      {autoGenerated && (
        <div className="absolute top-3 right-3 z-10">
          <Badge
            variant="outline"
            className="bg-amber-50 text-amber-600 border-amber-200 text-[10px] font-semibold tracking-wide px-2 py-0.5"
          >
            <Zap className="w-3 h-3 mr-1 fill-amber-400 text-amber-500" />
            AI Auto-Generated
          </Badge>
        </div>
      )}

      <CardContent className="p-5 flex flex-col h-full min-h-[180px]">
        {/* Header: Icon + Name */}
        <div className="flex items-start gap-3 mb-3">
          <div
            className={`
              shrink-0 w-10 h-10 rounded-xl flex items-center justify-center
              ${enabled
                ? 'bg-primary/10 text-primary'
                : 'bg-muted text-muted-foreground'
              }
              transition-colors duration-200
            `}
          >
            <IconComponent className="w-5 h-5" />
          </div>
          <div className="min-w-0 flex-1">
            <h3 className="font-semibold text-sm text-foreground leading-tight truncate">
              {name}
            </h3>
            <Badge
              variant="secondary"
              className="mt-1 text-[10px] px-1.5 py-0 h-4 font-normal"
            >
              {categoryLabels[category] || category}
            </Badge>
          </div>
        </div>

        {/* Description */}
        <p className="text-xs text-muted-foreground leading-relaxed mb-4 flex-1 line-clamp-2">
          {description}
        </p>

        {/* Footer: Source + Toggle */}
        <div className="flex items-center justify-between mt-auto pt-3 border-t border-border/40">
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <span
              className={`w-2 h-2 rounded-full ${enabled ? 'bg-emerald-500' : 'bg-slate-300'}`}
            />
            <span>{enabled ? '已启用' : '未启用'}</span>
          </div>
          <Switch
            checked={enabled}
            onCheckedChange={(checked) => onToggle(id, checked)}
            aria-label={`${name} 开关`}
          />
        </div>
      </CardContent>
    </Card>
  );
};

// ─────────────────────────────────────────────
// Toast Component
// ─────────────────────────────────────────────

interface ToastProps {
  toast: ToastState;
  onDismiss: () => void;
}

const Toast: React.FC<ToastProps> = ({ toast, onDismiss }) => {
  useEffect(() => {
    if (toast.visible) {
      const timer = setTimeout(onDismiss, 2500);
      return () => clearTimeout(timer);
    }
  }, [toast.visible, onDismiss]);

  if (!toast.visible) return null;

  return (
    <div className="fixed bottom-6 right-6 z-50 animate-in slide-in-from-bottom-2 fade-in duration-300">
      <div
        className={`
          flex items-center gap-2 px-4 py-3 rounded-lg shadow-lg border text-sm font-medium
          ${toast.type === 'success'
            ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
            : 'bg-red-50 text-red-700 border-red-200'
          }
        `}
      >
        <span
          className={`w-2 h-2 rounded-full ${toast.type === 'success' ? 'bg-emerald-500' : 'bg-red-500'}`}
        />
        {toast.message}
      </div>
    </div>
  );
};

// ─────────────────────────────────────────────
// Stats Summary
// ─────────────────────────────────────────────

interface StatsSummaryProps {
  total: number;
  enabled: number;
  label: string;
}

const StatsSummary: React.FC<StatsSummaryProps> = ({ total, enabled, label }) => (
  <div className="flex items-center gap-3 text-xs text-muted-foreground mb-3 px-1">
    <span>
      共 <strong className="text-foreground">{total}</strong> 个{label}
    </span>
    <span className="w-px h-3 bg-border" />
    <span>
      已启用 <strong className="text-emerald-600">{enabled}</strong> 个
    </span>
    <span className="w-px h-3 bg-border" />
    <span>
      未启用 <strong className="text-slate-400">{total - enabled}</strong> 个
    </span>
  </div>
);

// ─────────────────────────────────────────────
// Main Component: SkillMarketTab
// ─────────────────────────────────────────────

const SkillMarketTab: React.FC = () => {
  // -- State --
  const [activeTab, setActiveTab] = useState<'tools' | 'skills'>('tools');
  const [searchQuery, setSearchQuery] = useState('');
  const [activeCategory, setActiveCategory] = useState('all');

  const [toolStates, setToolStates] = useState<Record<string, boolean>>(
    Object.fromEntries(mcpTools.map((t) => [t.id, t.enabled]))
  );
  const [skillStates, setSkillStates] = useState<Record<string, boolean>>(
    Object.fromEntries(skills.map((s) => [s.id, s.enabled]))
  );

  const [toast, setToast] = useState<ToastState>({
    message: '',
    type: 'success',
    visible: false,
  });

  // -- Categories per tab --
  const toolCategories = useMemo(() => {
    const cats = new Set(mcpTools.map((t) => t.category));
    return ['all', ...Array.from(cats)];
  }, []);

  const skillCategories = useMemo(() => {
    const cats = new Set(skills.map((s) => s.category));
    return ['all', ...Array.from(cats)];
  }, []);

  const currentCategories = activeTab === 'tools' ? toolCategories : skillCategories;

  // -- Filtered items --
  const filteredTools = useMemo(() => {
    return mcpTools.filter((tool) => {
      const matchesSearch =
        !searchQuery ||
        tool.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        tool.description.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesCategory =
        activeCategory === 'all' || tool.category === activeCategory;
      return matchesSearch && matchesCategory;
    });
  }, [searchQuery, activeCategory]);

  const filteredSkills = useMemo(() => {
    return skills.filter((skill) => {
      const matchesSearch =
        !searchQuery ||
        skill.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        skill.description.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesCategory =
        activeCategory === 'all' || skill.category === activeCategory;
      return matchesSearch && matchesCategory;
    });
  }, [searchQuery, activeCategory]);

  // -- Toggle handler --
  const showToast = useCallback((message: string, type: ToastType) => {
    setToast({ message, type, visible: true });
  }, []);

  const dismissToast = useCallback(() => {
    setToast((prev) => ({ ...prev, visible: false }));
  }, []);

  const handleToggleTool = useCallback(
    (id: string, enabled: boolean) => {
      setToolStates((prev) => ({ ...prev, [id]: enabled }));
      const tool = mcpTools.find((t) => t.id === id);
      const name = tool?.name || id;
      // Simulate API call
      setTimeout(() => {
        showToast(
          `${enabled ? '已启用' : '已禁用'} MCP 插件：${name}`,
          'success'
        );
      }, 200);
    },
    [showToast]
  );

  const handleToggleSkill = useCallback(
    (id: string, enabled: boolean) => {
      setSkillStates((prev) => ({ ...prev, [id]: enabled }));
      const skill = skills.find((s) => s.id === id);
      const name = skill?.name || id;
      // Simulate API call
      setTimeout(() => {
        showToast(
          `${enabled ? '已启用' : '已禁用'} 技能：${name}`,
          'success'
        );
      }, 200);
    },
    [showToast]
  );

  // -- Reset category on tab switch --
  const handleTabChange = useCallback((value: string) => {
    setActiveTab(value as 'tools' | 'skills');
    setActiveCategory('all');
    setSearchQuery('');
  }, []);

  return (
    <div className="w-full h-full flex flex-col">
      {/* ── Header ── */}
      <div className="shrink-0 mb-5">
        <h2 className="text-lg font-bold text-foreground flex items-center gap-2 mb-4">
          <Plug className="w-5 h-5 text-primary" />
          技能与插件市场
        </h2>

        {/* Tabs */}
        <Tabs
          value={activeTab}
          onValueChange={handleTabChange}
        >
          <TabsList className="w-full grid grid-cols-2 h-11">
            <TabsTrigger
              value="tools"
              className="flex items-center gap-2 text-sm font-medium data-[state=active]:bg-background data-[state=active]:shadow-sm"
            >
              <Plug className="w-4 h-4" />
              MCP 硬件外设
              <span className="text-[10px] text-muted-foreground ml-1">
                ({mcpTools.length})
              </span>
            </TabsTrigger>
            <TabsTrigger
              value="skills"
              className="flex items-center gap-2 text-sm font-medium data-[state=active]:bg-background data-[state=active]:shadow-sm"
            >
              <Brain className="w-4 h-4" />
              大脑认知技能
              <span className="text-[10px] text-muted-foreground ml-1">
                ({skills.length})
              </span>
            </TabsTrigger>
          </TabsList>
        </Tabs>
      </div>

      {/* ── Search & Filter Bar ── */}
      <div className="shrink-0 flex flex-col gap-3 mb-4">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground pointer-events-none" />
          <Input
            type="text"
            placeholder={
              activeTab === 'tools'
                ? '搜索 MCP 插件名称或描述...'
                : '搜索技能名称或描述...'
            }
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-9 h-10 text-sm bg-muted/40 border-muted focus:bg-background"
          />
        </div>

        <CategoryTabBar
          categories={currentCategories}
          active={activeCategory}
          onSelect={setActiveCategory}
        />
      </div>

      {/* ── Content ── */}
      <div className="flex-1 overflow-y-auto min-h-0 pr-1">
        {/* Tools Tab Content */}
        {activeTab === 'tools' && (
          <div>
            <StatsSummary
              total={filteredTools.length}
              enabled={filteredTools.filter((t) => toolStates[t.id]).length}
              label="插件"
            />
            {filteredTools.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
                <Plug className="w-10 h-10 mb-3 opacity-40" />
                <p className="text-sm">未找到匹配的 MCP 插件</p>
                <p className="text-xs mt-1 opacity-60">
                  尝试调整搜索关键词或分类筛选
                </p>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 pb-4">
                {filteredTools.map((tool) => (
                  <CardItem
                    key={tool.id}
                    id={tool.id}
                    name={tool.name}
                    description={tool.description}
                    category={tool.category}
                    icon={tool.icon}
                    enabled={toolStates[tool.id] ?? tool.enabled}
                    source={tool.source}
                    onToggle={handleToggleTool}
                  />
                ))}
              </div>
            )}
          </div>
        )}

        {/* Skills Tab Content */}
        {activeTab === 'skills' && (
          <div>
            <StatsSummary
              total={filteredSkills.length}
              enabled={filteredSkills.filter((s) => skillStates[s.id]).length}
              label="技能"
            />
            {filteredSkills.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
                <Brain className="w-10 h-10 mb-3 opacity-40" />
                <p className="text-sm">未找到匹配的技能</p>
                <p className="text-xs mt-1 opacity-60">
                  尝试调整搜索关键词或分类筛选
                </p>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 pb-4">
                {filteredSkills.map((skill) => (
                  <CardItem
                    key={skill.id}
                    id={skill.id}
                    name={skill.name}
                    description={skill.description}
                    category={skill.category}
                    icon={skill.icon}
                    enabled={skillStates[skill.id] ?? skill.enabled}
                    autoGenerated={skill.autoGenerated}
                    source={skill.source}
                    onToggle={handleToggleSkill}
                  />
                ))}
              </div>
            )}
          </div>
        )}
      </div>

      {/* ── Toast ── */}
      <Toast toast={toast} onDismiss={dismissToast} />
    </div>
  );
};

export default SkillMarketTab;
